apiVersion: v1
kind: Secret
metadata:
  name: minio-secret-tempostack
  namespace: {{ .Release.Namespace }}
stringData:
  endpoint: {{ .Values.minioEndpoint }}
  insecure: "false"
  bucket: {{ .Values.minioBucket }}
  access_key_id: {{ .Values.minioKey }}
  access_key_secret: {{ .Values.minioSecret }}
type: Opaque